import { useState, useMemo } from 'react';

import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Container,Card, Text, Button,Input,Spacer, Table } from '@nextui-org/react';

export default function Home() {


  const [numberOfPizzas, setNumberOfPizzas] = useState(1)
  const [sizeOfPizza, setSizeOfPizza] = useState(160)
  const [hydration, setHydration] = useState(60)

  const onChangeNumberOfPizzas = (event: React.ChangeEvent<HTMLInputElement>) =>{
    setNumberOfPizzas(parseInt(event.target.value))
  }

  const onChangeSizeOfPizza = (event: React.ChangeEvent<HTMLInputElement>) =>{
    setSizeOfPizza(parseInt(event.target.value))
  }

  const onChangeHydration = (event: React.ChangeEvent<HTMLInputElement>) =>{
    setHydration(parseInt(event.target.value))
  }

  const flour = useMemo(
    () =>
    Math.floor((100 * sizeOfPizza / (100 + hydration)) * numberOfPizzas),
    [numberOfPizzas, sizeOfPizza, hydration]
  )

  const water = useMemo(() => flour * hydration / 100, [hydration, flour])

  console.log("numberOfPizzas")
  console.log(numberOfPizzas)

  console.log("sizeOfPizza")
  console.log(sizeOfPizza)

  console.log("hydration")
  console.log(hydration)

  console.log("100 * sizeOfPizza")
  console.log(100 * sizeOfPizza)

  console.log("100 + hydration")
  console.log(100 + hydration)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Text h1>Pizza Dough Calculator</Text>
        <Spacer y={2} />
        <Card css={{ mw: "400px" }}>
          <Card.Body>
            <Input 
              label="Number of pizzas" 
              type="number"
              value={numberOfPizzas}
              onChange={onChangeNumberOfPizzas}
            />
            <Spacer y={1} />
            <Input 
              label="Size of pizza" 
              type="number" 
              value={sizeOfPizza}
              onChange={onChangeSizeOfPizza}
            />
            <Spacer y={1} />
            <Input 
              label="Hydration" 
              type="number" 
              value={hydration}
              onChange={onChangeHydration}
              max={100}
              min={0}
            />
          </Card.Body>
        </Card>
        <Spacer y={2} />
        <Text h2> Result</Text>
        <Table
          aria-label="Example table with static content"
          bordered
          shadow={false}
          css={{
            height: "auto",
            width: "400px" 
          }}
        >
          <Table.Header>
            <Table.Column>Ingredient</Table.Column>
            <Table.Column>Amount</Table.Column>
          </Table.Header>
          <Table.Body>
            <Table.Row key="1">
              <Table.Cell>Flour</Table.Cell>
              <Table.Cell>{flour} g</Table.Cell>
            </Table.Row>
            <Table.Row key="2">
              <Table.Cell>Water</Table.Cell>
              <Table.Cell>{water} ml</Table.Cell>
            </Table.Row>
          </Table.Body>
        </Table>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
